// Mock data to use when MongoDB is not connected

export const mockFarms = [
  {
    _id: '1',
    farmName: 'Green Valley Farm',
    farmerName: 'Rajesh Kumar',
    nearestCity: 'Ludhiana',
    state: 'Punjab',
    latitude: 30.9293,
    longitude: 75.5003,
    cropType: 'Wheat',
    cropQuantity: 5000,
    availableQuantity: 3000,
    harvestDate: new Date('2024-03-15'),
    predictedYield: 4800,
    weatherCondition: 'Good',
    fertilizerUsed: 'Organic',
    marketPrice: 25.50,
    qualityRating: 4.5,
    contactNumber: '+919876543210',
    email: 'rajesh@farm.com',
    bulkPurchaseDiscount: 10,
    minimumBulkQuantity: 500,
  },
  {
    _id: '2',
    farmName: 'Golden Fields',
    farmerName: 'Suresh Singh',
    nearestCity: 'Amritsar',
    state: 'Punjab',
    latitude: 31.6340,
    longitude: 74.8723,
    cropType: 'Rice',
    cropQuantity: 8000,
    availableQuantity: 6000,
    harvestDate: new Date('2024-04-20'),
    predictedYield: 7500,
    weatherCondition: 'Excellent',
    fertilizerUsed: 'NPK',
    marketPrice: 30.00,
    qualityRating: 4.8,
    contactNumber: '+919876543211',
    email: 'suresh@farm.com',
    bulkPurchaseDiscount: 15,
    minimumBulkQuantity: 1000,
  },
  {
    _id: '3',
    farmName: 'Sunshine Farm',
    farmerName: 'Amit Patel',
    nearestCity: 'Ahmedabad',
    state: 'Gujarat',
    latitude: 23.0225,
    longitude: 72.5714,
    cropType: 'Cotton',
    cropQuantity: 12000,
    availableQuantity: 9000,
    harvestDate: new Date('2024-05-10'),
    predictedYield: 11000,
    weatherCondition: 'Normal',
    fertilizerUsed: 'Mixed',
    marketPrice: 45.75,
    qualityRating: 4.2,
    contactNumber: '+919876543212',
    email: 'amit@farm.com',
    bulkPurchaseDiscount: 12,
    minimumBulkQuantity: 800,
  },
  {
    _id: '4',
    farmName: 'Harvest Haven',
    farmerName: 'Vikram Sharma',
    nearestCity: 'Karnal',
    state: 'Haryana',
    latitude: 29.0588,
    longitude: 76.0856,
    cropType: 'Sugarcane',
    cropQuantity: 15000,
    availableQuantity: 12000,
    harvestDate: new Date('2024-06-01'),
    predictedYield: 14500,
    weatherCondition: 'Good',
    fertilizerUsed: 'DAP',
    marketPrice: 35.00,
    qualityRating: 4.6,
    contactNumber: '+919876543213',
    email: 'vikram@farm.com',
    bulkPurchaseDiscount: 18,
    minimumBulkQuantity: 1500,
  },
  {
    _id: '5',
    farmName: 'Crop Masters',
    farmerName: 'Ramesh Yadav',
    nearestCity: 'Lucknow',
    state: 'Uttar Pradesh',
    latitude: 26.8467,
    longitude: 80.9462,
    cropType: 'Maize',
    cropQuantity: 7000,
    availableQuantity: 5000,
    harvestDate: new Date('2024-03-25'),
    predictedYield: 6800,
    weatherCondition: 'Fair',
    fertilizerUsed: 'Urea',
    marketPrice: 22.50,
    qualityRating: 4.0,
    contactNumber: '+919876543214',
    email: 'ramesh@farm.com',
    bulkPurchaseDiscount: 8,
    minimumBulkQuantity: 600,
  },
  {
    _id: '6',
    farmName: 'Organic Oasis',
    farmerName: 'Mohan Das',
    nearestCity: 'Pune',
    state: 'Maharashtra',
    latitude: 18.5204,
    longitude: 73.8567,
    cropType: 'Soybean',
    cropQuantity: 6000,
    availableQuantity: 4000,
    harvestDate: new Date('2024-04-05'),
    predictedYield: 5800,
    weatherCondition: 'Excellent',
    fertilizerUsed: 'Organic',
    marketPrice: 40.00,
    qualityRating: 4.9,
    contactNumber: '+919876543215',
    email: 'mohan@farm.com',
    bulkPurchaseDiscount: 20,
    minimumBulkQuantity: 500,
  },
  {
    _id: '7',
    farmName: 'Fresh Fields',
    farmerName: 'Kiran Reddy',
    nearestCity: 'Bangalore',
    state: 'Karnataka',
    latitude: 12.9716,
    longitude: 77.5946,
    cropType: 'Potato',
    cropQuantity: 10000,
    availableQuantity: 8000,
    harvestDate: new Date('2024-02-20'),
    predictedYield: 9500,
    weatherCondition: 'Good',
    fertilizerUsed: 'NPK',
    marketPrice: 18.75,
    qualityRating: 4.3,
    contactNumber: '+919876543216',
    email: 'kiran@farm.com',
    bulkPurchaseDiscount: 10,
    minimumBulkQuantity: 1000,
  },
  {
    _id: '8',
    farmName: 'Veggie Valley',
    farmerName: 'Prakash Nair',
    nearestCity: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0827,
    longitude: 80.2707,
    cropType: 'Tomato',
    cropQuantity: 5000,
    availableQuantity: 3500,
    harvestDate: new Date('2024-03-10'),
    predictedYield: 4800,
    weatherCondition: 'Normal',
    fertilizerUsed: 'Organic',
    marketPrice: 28.50,
    qualityRating: 4.4,
    contactNumber: '+919876543217',
    email: 'prakash@farm.com',
    bulkPurchaseDiscount: 12,
    minimumBulkQuantity: 500,
  },
  {
    _id: '9',
    farmName: 'Spice Garden',
    farmerName: 'Anil Mehta',
    nearestCity: 'Jaipur',
    state: 'Rajasthan',
    latitude: 26.9124,
    longitude: 75.7873,
    cropType: 'Chilli',
    cropQuantity: 4000,
    availableQuantity: 3000,
    harvestDate: new Date('2024-04-15'),
    predictedYield: 3800,
    weatherCondition: 'Good',
    fertilizerUsed: 'Mixed',
    marketPrice: 55.00,
    qualityRating: 4.7,
    contactNumber: '+919876543218',
    email: 'anil@farm.com',
    bulkPurchaseDiscount: 15,
    minimumBulkQuantity: 400,
  },
  {
    _id: '10',
    farmName: 'Herb Haven',
    farmerName: 'Sunil Gupta',
    nearestCity: 'Kolkata',
    state: 'West Bengal',
    latitude: 22.5726,
    longitude: 88.3639,
    cropType: 'Turmeric',
    cropQuantity: 3000,
    availableQuantity: 2500,
    harvestDate: new Date('2024-05-05'),
    predictedYield: 2900,
    weatherCondition: 'Excellent',
    fertilizerUsed: 'Organic',
    marketPrice: 65.00,
    qualityRating: 4.8,
    contactNumber: '+919876543219',
    email: 'sunil@farm.com',
    bulkPurchaseDiscount: 18,
    minimumBulkQuantity: 300,
  },
];

export const mockCrops = [
  {
    _id: '1',
    cropName: 'Wheat',
    cropType: 'Wheat',
    totalQuantity: 5000,
    availableQuantity: 3000,
    averagePrice: 25.50,
    topProducingStates: [
      { state: 'Punjab', quantity: 3000 },
      { state: 'Haryana', quantity: 2000 },
    ],
    season: 'Rabi',
    harvestMonths: ['March', 'April'],
  },
  {
    _id: '2',
    cropName: 'Rice',
    cropType: 'Rice',
    totalQuantity: 8000,
    availableQuantity: 6000,
    averagePrice: 30.00,
    topProducingStates: [
      { state: 'Punjab', quantity: 6000 },
      { state: 'West Bengal', quantity: 2000 },
    ],
    season: 'Kharif',
    harvestMonths: ['September', 'October'],
  },
  {
    _id: '3',
    cropName: 'Cotton',
    cropType: 'Cotton',
    totalQuantity: 12000,
    availableQuantity: 9000,
    averagePrice: 45.75,
    topProducingStates: [
      { state: 'Gujarat', quantity: 9000 },
      { state: 'Maharashtra', quantity: 3000 },
    ],
    season: 'Kharif',
    harvestMonths: ['October', 'November'],
  },
  {
    _id: '4',
    cropName: 'Sugarcane',
    cropType: 'Sugarcane',
    totalQuantity: 15000,
    availableQuantity: 12000,
    averagePrice: 35.00,
    topProducingStates: [
      { state: 'Uttar Pradesh', quantity: 8000 },
      { state: 'Maharashtra', quantity: 4000 },
    ],
    season: 'All Season',
    harvestMonths: ['December', 'January'],
  },
  {
    _id: '5',
    cropName: 'Maize',
    cropType: 'Maize',
    totalQuantity: 7000,
    availableQuantity: 5000,
    averagePrice: 22.50,
    topProducingStates: [
      { state: 'Karnataka', quantity: 3000 },
      { state: 'Uttar Pradesh', quantity: 2000 },
    ],
    season: 'Kharif',
    harvestMonths: ['September', 'October'],
  },
  {
    _id: '6',
    cropName: 'Soybean',
    cropType: 'Soybean',
    totalQuantity: 6000,
    availableQuantity: 4000,
    averagePrice: 40.00,
    topProducingStates: [
      { state: 'Madhya Pradesh', quantity: 2500 },
      { state: 'Maharashtra', quantity: 1500 },
    ],
    season: 'Kharif',
    harvestMonths: ['October', 'November'],
  },
  {
    _id: '7',
    cropName: 'Potato',
    cropType: 'Potato',
    totalQuantity: 10000,
    availableQuantity: 8000,
    averagePrice: 18.75,
    topProducingStates: [
      { state: 'Uttar Pradesh', quantity: 4000 },
      { state: 'West Bengal', quantity: 4000 },
    ],
    season: 'Rabi',
    harvestMonths: ['January', 'February'],
  },
  {
    _id: '8',
    cropName: 'Tomato',
    cropType: 'Tomato',
    totalQuantity: 5000,
    availableQuantity: 3500,
    averagePrice: 28.50,
    topProducingStates: [
      { state: 'Andhra Pradesh', quantity: 2000 },
      { state: 'Karnataka', quantity: 1500 },
    ],
    season: 'All Season',
    harvestMonths: ['March', 'April', 'May'],
  },
  {
    _id: '9',
    cropName: 'Onion',
    cropType: 'Onion',
    totalQuantity: 6000,
    availableQuantity: 4500,
    averagePrice: 32.00,
    topProducingStates: [
      { state: 'Maharashtra', quantity: 3000 },
      { state: 'Karnataka', quantity: 1500 },
    ],
    season: 'Rabi',
    harvestMonths: ['March', 'April'],
  },
  {
    _id: '10',
    cropName: 'Chilli',
    cropType: 'Chilli',
    totalQuantity: 4000,
    availableQuantity: 3000,
    averagePrice: 55.00,
    topProducingStates: [
      { state: 'Andhra Pradesh', quantity: 2000 },
      { state: 'Karnataka', quantity: 1000 },
    ],
    season: 'Kharif',
    harvestMonths: ['September', 'October'],
  },
  {
    _id: '11',
    cropName: 'Turmeric',
    cropType: 'Turmeric',
    totalQuantity: 3000,
    availableQuantity: 2500,
    averagePrice: 65.00,
    topProducingStates: [
      { state: 'Tamil Nadu', quantity: 1500 },
      { state: 'Andhra Pradesh', quantity: 1000 },
    ],
    season: 'Kharif',
    harvestMonths: ['January', 'February'],
  },
  {
    _id: '12',
    cropName: 'Ginger',
    cropType: 'Ginger',
    totalQuantity: 3500,
    availableQuantity: 2800,
    averagePrice: 70.00,
    topProducingStates: [
      { state: 'Kerala', quantity: 1500 },
      { state: 'Karnataka', quantity: 1300 },
    ],
    season: 'Kharif',
    harvestMonths: ['December', 'January'],
  },
];

